include: package:very_good_analysis/analysis_options.yaml
analyzer:

  plugins:
    - dart_code_metrics

dart_code_metrics:
  anti-patterns:
    - long-method
    - long-parameter-list
  metrics:
    number-of-parameters: 3
    lines-of-code: 50
    number-of-methods: 30
    source-lines-of-code: 50

  metrics-exclude:
    - test/**
  rules-exclude:
    - test/**
  rules:

    - avoid-redundant-async
    - avoid-unnecessary-type-assertions
    - avoid-unnecessary-type-casts
    - avoid-unrelated-type-assertions
    - avoid-unused-parameters
    - avoid-nested-conditional-expressions
    - avoid-nested-conditional-expressions
    - no-boolean-literal-compare
    - no-empty-block
    - avoid-collection-methods-with-unrelated-types
    - avoid-returning-widgets
    - list-all-equatable-fields
    - avoid-non-ascii-symbols
    - avoid-returning-widgets
    - prefer-immediate-return
    - prefer-conditional-expressions
    - no-equal-then-else

linter:
  rules:
    public_member_api_docs: false
