name: wizr
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  bloc: ^8.1.2
  dio: ^5.1.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_dotenv: ^5.0.2
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.6
  get: ^4.6.5
  get_it: ^7.6.0
  go_router: ^8.0.0
  intl: ^0.18.0
  molten_navigationbar_flutter: ^1.0.1

dev_dependencies:
  bloc_test: ^9.1.2
  build_runner: ^2.4.4
  dart_code_metrics: ^5.7.4
  flutter_gen_runner: ^5.3.1
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^5.0.0



flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
  fonts:
    - family: Patron
      fonts:
        - asset: assets/fonts/Patron-Bold.ttf
          weight: 700
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
          weight: 400
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600
