name: wizr
description: A Very Good Project created by Very Good CLI.
version: 1.0.1+3
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  bloc: ^8.1.2
  device_preview: ^1.1.0
  dio: ^5.1.2
  face_camera: ^0.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_dotenv: ^5.0.2
  flutter_localizations:
    sdk: flutter
  flutter_screenutil: ^5.8.4
  flutter_staggered_animations: ^1.1.1
  flutter_staggered_grid_view: ^0.6.2
  flutter_svg: ^2.0.6
  fluttertoast: ^8.2.2
  get: ^4.6.5
  get_it: ^7.6.0
  go_router: ^9.0.0
  intl: ^0.18.0
  permission_handler: ^10.3.0
  pinput: ^2.2.31
  simple_ripple_animation: ^0.0.7
  sleek_circular_slider: ^2.0.1
  step_progress_indicator: ^1.0.2

dev_dependencies:
  bloc_test: ^9.1.2
  build_runner: ^2.4.4
  dart_code_metrics: ^5.7.4
  flutter_gen_runner: ^5.3.1
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^5.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
    - assets/icons/
  fonts:
    - family: Patron
      fonts:
        - asset: assets/fonts/Patron-Bold.otf
          weight: 700

    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
          weight: 400
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600

    - family: Quintus
      fonts:
        - asset: assets/fonts/Quintus-Bold-Trial.ttf
          weight: 700
