name: wizr
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  bloc: ^8.1.2
  dio: ^5.1.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_dotenv: ^5.0.2
  flutter_localizations:
    sdk: flutter
  get: ^4.6.5
  get_it: ^7.6.0
  go_router: ^7.1.1
  intl: ^0.18.0

dev_dependencies:
  bloc_test: ^9.1.2
  dart_code_metrics: ^5.7.4
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^5.0.0

flutter_gen:
  output: lib/utils/asset_paths.dart # Optional (default: lib/gen/)
  line_length: 80 # Optional (default: 80)

  # Optional
  integrations:
    flutter_svg: true
  assets:
    outputs:

      style: camel-case
      class_name: Assets



flutter:
  uses-material-design: true
  generate: true
